### PR TITLE
Rebase next into master

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Take all of the changes in the `next` branch, and rebase them on over to `master`.  After this, we'll be ready to release 1.0.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@ofrobots what's up with the CLA bot here?

**Comment by ofrobots** [comment]
CLA bot doesn't like it when commits from multiple authors are present in a PR. Looking over all the commits, it seems everything commit has CLAs in place.

**Comment by ofrobots** [comment]
DO NOT LAND USING SQUASH AND MERGE.

**Comment by JustinBeckwith** [comment]
Is the "rebase and merge" button ok?  Or should I just `git push upstream master`?

**Comment by ofrobots** [comment]
Please push manually.

Side note: rebase + merge should be disable in the repo settings.

**Pull request merged**
