### PR TITLE
Move code from lib/ to src/

### PR DESCRIPTION
**Pull request by ofrobots**
To be transpiled source shouldn't exist in `lib`.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
In general, LGTM.  It is however, a breaking change.  How are we communicating those to users?

**Comment by ofrobots** [comment]
In a follow-on PR, I can address the concern about the directory path changing being a breaking change for external users who are deep requiring files directly. I will modify the gulp configuration so that generated files do end up in `lib/`.

**Comment by ofrobots** [comment]
Added a commit here that modifies the gulpfile to make sure the output js files are produced in lib/. This commit also enables the generation of .d.ts files.

**Comment by ofrobots** [comment]
Avoiding a semver major is slightly more complicated than originally thought. Tests depend upon relative paths to the source files which don't look the same if the directory structure changes. e.g.

```
import GoogleAuth from '../src/auth/googleauth';
```

**Comment by ofrobots** [comment]
Superceded by #144

**Pull request closed without merging**
