### PR TITLE
state is a valid option of GenerateAuthUrlOpts

### PR DESCRIPTION
**Pull request by stevemao**
See https://auth0.com/docs/protocols/oauth2/oauth-state

### CODE REVIEW

**Comment by lukesneeringer** [comment]
@bantini Please check the spec, ensure validity, and add a test and submit this PR if so.

**Comment by stevemao** [comment]
This is a ts type signature change which involves no functionality changes. I don't know if we need to write a test against a type signature.

**Comment by JustinBeckwith** [comment]
*shrugs* if it's just a typing fix, I don't think we need a test.

**Comment by JustinBeckwith** [comment]
Addressed by #184.  Thanks!

**Pull request closed without merging**
