### PR TITLE
Initial conversion to core HTTP

### PR DESCRIPTION
**Pull request by cristiancavalli**
Opening this so work may be observed as it progresses.
In this opening commit:
- Convert `transporters.js` to use the `http` module over `request`
- Change tests to correctly test changes of internal modules.

Goals: Preserve breadth of functionality without changing API surface while swapping out `request` in favor of `http`

To do:
- [x] Create validations on mocked services to ensure headers
- [x] Create docker integration tests between library and dependents.
- [x] Document new HTTP wrapper implementation

### CODE REVIEW

**Comment by cristiancavalli** [comment]
cc @google/google-node-team @jmdobry @stephenplusplus

**Comment by cristiancavalli** [comment]
@google/google-node-team this is ready to start being reviewed. I now have verified using docker and google-auto-auth that basic acceptance testing is also working

**Comment by jmdobry** [comment]
Before merging this I think we need to test it against our other client libraries that use google-auth-library-nodejs. @stephenplusplus says something like this should work:

```
google-auth-library-nodejs
google-auto-auth
google-gax
google-cloud-node

cd google-auth-library-nodejs # on correct branch
npm link

cd google-auto-auth
npm link google-auth-library

cd google-gax
npm link google-auto-auth

cd google-cloud-node
cd packages/common
npm link google-auto-auth
cd ../../
cd packages/logging
npm link google-auto-auth
cd ../../
npm run link-common
npm run system-test
```

**Comment by JustinBeckwith** [comment]
Any progress here?  #135 is getting moldy :)

**Comment by ofrobots** [comment]
I don't think #135 should wait for this.

This PR includes some cleanup and refactorings at the same time as the changes to the http transport. It would be better to tease these two things apart so that we can reduce the changes.

Here's my proposed plan of action: Once #135 has landed, rebase it on top of that. Split distinct cleanup portions into separate PRs.

**Comment by lukesneeringer** [comment]
Closing in favor of #166.

**Pull request closed without merging**
