### PR TITLE
Fix usage of OAuth2Client.verifyIdToken in example

### PR DESCRIPTION
**Pull request by aknuds1**
examples/verifyIdToken.js uses the old signature for `OAuth2Client.verifyIdToken`, this PR upgrades it to the new API.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Thank you for catching this :)  Could you also add the audience in the new options?  

```js
const ticket = await oAuth2Client.verifyIdToken({
  idToken: oAuth2Client.credentials.id_token,
  audience: keys.web.client_id
});
```

**Comment by aknuds1** [comment]
@JustinBeckwith I added a part `audience: 'audience'` to the `verifyIdToken` options, as I don't know would be a sensible value for `audience`. Does this look OK to you or should I use some other value?

**Comment by aknuds1** [comment]
@JustinBeckwith I'm also wondering if `verifyIdToken` should be documented somewhere? I only find it in examples and tests.

**Comment by JustinBeckwith** [comment]
The audience should be set to `keys.web.client_id` :) On the docs piece - the readme can always be better, but at least we have a proper reference doc now at google.github.io/google-auth-library-nodejs/

**Comment by aknuds1** [comment]
@JustinBeckwith Oh, alright, I've updated the PR. The `verifyIdToken` test (test.oauth2.ts) doesn't follow this pattern though, should it be changed to read `const result = await client.verifyIdToken({idToken, audience: CLIENT_ID, maxExpiry});` to be consistent?

**Comment by Boboss74** [comment]
omg this is why it doesn't work... T-T

**Pull request merged**
