### PR TITLE
chore: license check as posttest

### PR DESCRIPTION
**Pull request by jinwoo**

### CODE REVIEW

**Comment by jinwoo** [comment]
Tests fail with errors that are unrelated to this PR. Any idea anyone?

```
[22:21:40] Error: no writecb in Transform class
    at afterTransform (/home/travis/build/google/google-auth-library-nodejs/node_modules/gulp-clang-format/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at TransformState.afterTransform (/home/travis/build/google/google-auth-library-nodejs/node_modules/gulp-clang-format/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at ChildProcess.<anonymous> (/home/travis/build/google/google-auth-library-nodejs/node_modules/clang-format/index.js:117:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

**Comment by jinwoo** [comment]
Tests pass locally but fail in CI, and failures are not related to the changes in this PR. They are from `gulp test.check-format`.

**Comment by JustinBeckwith** [comment]
Sorry to do this, but could you please re-base this PR against the `next` branch?

**Comment by jinwoo** [comment]
@JustinBeckwith So is `master` currently broken? I'll try rebasing against `next`. Or abandon this and create a new one.

**Comment by jinwoo** [comment]
Abandoning this. Will create a new PR against `next`.

**Pull request closed without merging**
